version: '3.1'
services:
  reverse_proxy:
    image: jwilder/nginx-proxy
    restart: always
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - /home/ec2-user/certs:/etc/nginx/certs:ro
    - /etc/nginx/vhost.d
    - /usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
  
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - /home/ec2-user/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - reverse_proxy:rw
  front:
    container_name: front-docker
    image: front-docker
    restart: always
    environment:
      - VIRTUAL_HOST=bookstore-telematica.ml,www.bookstore-telematica.ml
      - LETSENCRYPT_HOST=bookstore-telematica.ml,www.bookstore-telematica.ml
      - LETSENCRYPT_EMAIL=svelezp9@eafit.edu.co    
